---
title: "Introdução à análise geoespacial com R <br><br><br>"
subtitle: "6 Estrutura e manejo de dados vetoriais <br><br><br>"
author: "Maurício H. Vancine <br> Milton C. Ribeiro"
date: "22/10/2020"
output:
  xaringan::moon_reader:
    css: [metropolis, metropolis-fonts]
    lib_dir: libs
    nature:
      highlightStyle: rainbow
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup}
options(htmltools.dir.version = FALSE, encoding = "UTF-8")
knitr::opts_chunk$set(fig.retina = 3, warning = FALSE, message = FALSE)
```

---

# 6.3 Classes sf

## A classe sf

### Criar um objeto sf
```{r}
rc_point <- sf::st_point(c(-47.57,-22.39))         # sfg object
rc_geom <- sf::st_sfc(rc_point, crs = 4326)        # sfc object
rc_attrib <- data.frame(                       # data.frame object
  name = "Rio Claro",
  temperature = 19,
  date = as.Date("2020-10-13")
)
rc_sf <- sf::st_sf(rc_attrib, geometry = rc_geom)  # sf object
```

---

# 6.3 Classes sf

## A classe sf

### A estrutura de um objeto sf
```{r}
rc_sf
```

### As duas classes do objeto sf
```{r}
class(rc_sf)
```

---

# 6.3 Classes sf

## A classe sf

### Plot
```{r fig.align='center', out.width='45%'}
plot(rc_sf[1], pch = 20, cex = 4, axes = TRUE) # rc_sf[1] - plotar a primeira coluna
```